import PropTypes from 'prop-types';
import { PureComponent } from 'react';

import { injectIntl, defineMessages } from 'react-intl';

import { Helmet } from 'react-helmet';

import Column from 'mastodon/components/column';

const messages = defineMessages({
  title: { id: 'privacy_policy.title', defaultMessage: 'Privacy Policy' },
});

class PrivacyPolicy extends PureComponent {

  static propTypes = {
    intl: PropTypes.object,
    multiColumn: PropTypes.bool,
  };

  render () {
    const { intl, multiColumn } = this.props;

    return (
      <Column bindToDocument={!multiColumn} label={intl.formatMessage(messages.title)}>
        <div className='scrollable privacy-policy'>
          <h1>Acceptance of the Terms of Use</h1>
          <p>These Terms of Use are entered into by and between you and Cards Against Humanity (&quot;<strong>Company</strong>,&quot; &quot;<strong>we</strong>,&quot; or &quot;<strong>us</strong>&quot;). The following terms and conditions, together with any documents they expressly incorporate by reference, collectively (&quot;<strong>Terms of Use</strong>&quot;), govern your access to and use of the yowza.social website and app, including any content, functionality, and/or services offered on or through yowza.social (singularly, a &quot;<strong>Website</strong>,&quot; collectively the &quot;<strong>Websites</strong>&quot;).</p>
          <p>Please read these Terms of Use carefully before you start to the Websites. They are an agreement between you and us. <strong>By using the Websites, you acknowledge you have read, understand, accept and agree to be bound and abide by these Terms of Use and our Privacy Policy.</strong> If you do not want to agree to these Terms of Use and/or our Privacy Policy, you should not access or use either of the Websites.</p>
          <p>Cards Against Humanity and its Affiliated Entities (as defined below) collectively own, operate, and maintain cardsagainsthumanity.com and clams.lol and all of the various pages contained therein, including subdomains, and the related products and services whether provided through any website owned, maintained or controlled by us, through a social network, a mobile application, on a cellular telephone or otherwise, and provide the Websites subject to these Terms of Use.</p>
          <p>Cards Against Humanity includes Cards Against Humanity, LLC and its trustees, directors, officers, shareholders, members, employees, contractors, advisors, representatives, subcontractors, consultants, attorneys, agents, suppliers, distributors, licenses and licensors (current and past) and any affiliates, individually and collectively, and any related individuals or entities.</p>
          <p>Affiliated Parties means Cards Against Humanity, LLC and any related individuals, affiliates and subsidiaries, and any of their trustees, directors, officers, shareholders, members, employees, representatives, consultants, attorneys, agents, suppliers, distributors, licensees and/or licensors.</p>
          <p>The Websites are offered and available to users who are 13 years of age or older. By using the Websites, you represent and warrant that (a) you are of legal age to form a binding contract with us and meet all of the eligibility requirements contained herein, or (b) if you are under 18 years of age, your parent or guardian has permitted you to use the Websites; has read, understood, accepted, and agreed to be bound by these Terms of Use; and has agreed to be responsible for your activities in connection with the Websites. If you do not meet all of these requirements, you must not access or use the Websites.</p>
          <h2>Accessing the Websites</h2>
          <p>We reserve the right to withdraw or amend the Websites, and any service or material we provide, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Websites is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Websites, or the entire Websites, to users.</p>
          <p>You are responsible for both:</p>
          <ul>
            <li>Making all arrangements necessary for you to have access to the Websites.</li>
            <li>Ensuring that all persons who access the Websites through your internet connection are aware of these Terms of Use and comply with them.</li>
          </ul>
          <p>To access the Websites or some or all of the resources it offers, you may be asked to provide certain information. It is a condition of your use of the Websites that all the information you provide on the Websites is correct, accurate, current, and complete. You agree that all the information you provide to use the Websites or otherwise, including, but not limited to, through the use of any interactive features on the Websites, is also governed by our Privacy Policy, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
          <h2>Intellectual Property Rights</h2>
          <p>The Websites and their entire contents, features, and functionality (including but not limited to all information, features, functions, algorithms, know-how, code, data, art, graphics, animation, photographs, images, text, music, sound effects, audio elements, audio-video elements, software, text, displays, images, video, and audio, moral rights, downloadable materials, user interface, navigation, look and feel, and the design, selection, and arrangement thereof) are owned by the Company, its Affiliated Parties, licensors, and/or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
          <p>These Terms of Use permit you to use the Websites for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Websites, except as follows:</p>
          <ul>
            <li>Your computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials.</li>
          </ul>
          <p>You may store files that are automatically cached by your Web browser for display enhancement purposes.</p>
          <p>You must not:</p>
          <ul>
            <li>Modify copies of any materials from this site.</li>
            <li>Use any illustrations, photographs, video or audio sequences, or any graphics separately from the accompanying text.</li>
            <li>Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from the Websites.</li>
          </ul>
          <p>You must not access or use for any commercial purposes any part of the Websites or any services or products available through the Websites.</p>
          <p>If you print, copy, modify, download, or otherwise use or provide any other person with access to the Websites or any part(s) thereof in breach of these Terms of Use, your right to use the Websites will stop immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title, or interest in or to the Websites or any content on the Websites is transferred to you, and all rights not expressly granted are reserved by and to the Company. Any use of the Websites not expressly permitted by these Terms of Use is a breach of these Terms of Use and may also violate copyright, trademark, and other laws.</p>
          <h2>Prohibited Uses</h2>
          <p>You may use the Websites only for lawful purposes and in accordance with these Terms of Use. You agree not to use the Websites:</p>
          <ul>
            <li>In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the U.S. or other countries).</li>
            <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</li>
            <li>To send, knowingly receive, upload, download, use, or re-use any material that does not comply with these Terms of Use.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any &quot;junk mail,&quot; &quot;chain letter,&quot; &quot;spam,&quot; or any other similar solicitation.</li>
            <li>To impersonate or attempt to impersonate the Company, a Company employee, the employee(s) of any Affiliated Parties, another user, or any other person or entity (including, without limitation, by using email addresses associated with any of the foregoing).</li>
            <li>To engage in any other conduct that restricts or inhibits anyone&apos;s use or enjoyment of the Websites, or which, as determined by us, may harm the Company or users of the Websites, or expose them to liability.</li>
          </ul>
          <p>Additionally, you agree not to:</p>
          <ul>
            <li>Use the Websites in any manner that could disable, interrupt, overburden, damage, or impair the sites or interfere with any other party&apos;s use of the Websites, including their ability to engage in real time activities through the Websites.</li>
            <li>Use any robot, spider, or other automatic device, process, or means to access the Websites for any purpose, including monitoring or copying any of the material on the Websites.</li>
            <li>Modify, adapt, disassemble, decompile, translate, reverse engineer or otherwise attempt to discover the source code or structure, sequence and/or organization of our Websites or any portion thereof, except where required by applicable local law, and then only to the extent required by such law(s).</li>
            <li>Use any manual or automated process to monitor or copy any of the information on the Websites, or for any other purpose not expressly authorized in these Terms of Use, without our prior written consent.</li>
            <li>Use any device, software, or routine that automatically or manually interferes with the proper working of the Websites.</li>
            <li>Introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful and/or violate the security of any computer network or transfer or store illegal material.</li>
            <li>Use false information or impersonate any person or entity or misrepresent your affiliation with any other person or entity, whether actual or fictitious, include anyone from the Websites or any person or entity otherwise affiliated with us.</li>
            <li>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Websites, the server on which the Websites are stored, or any server, computer, or database connected to the Websites.</li>
            <li>Attack the Websites via a denial-of-service attack or a distributed denial-of-service attack.</li>
            <li>Engage in spamming, flooding, harvesting of email addresses or other personal information, or any other activity which is intended to obtain lists of users, their personally identifiable information or any other information we maintain about our Websites, visitors and customers.</li>
            <li>Post, upload, transmit, publish, reproduce or otherwise disseminate through the Site any Content that we determine in Our sole discretion is: (i) unlawful, harmful, harassing, fraudulent, threatening, abusive, libelous, defamatory, vulgar, obscene, hateful, inappropriate, discriminatory, or otherwise infringes our or any third party’s rights; (ii) is derogatory or harmful to our reputation or that of any affiliated individuals or entities, including Affiliated Parties; (iii) is harmful to children in any manner; and/or (iv) seeks to or discriminates against any individual based on race, gender, national origin, sexual preference, physical or mental handicap or on any other basis;</li>
            <li>Attempt (or encourage or support anyone else’s attempt) to circumvent, reverse-engineer, decrypt, or otherwise alter, or interfere with, the Site or any of its Content and/or Services;</li>
            <li>Submit false or misleading information to Us.</li>
            <li>Otherwise attempt to interfere with the proper working of the Websites or any of their security features.</li>
          </ul>
          <h2>Reliance on Information Posted</h2>
          <p>The information presented on or through the Websites is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor(s) to the Websites, or by anyone who may be informed of any of the contents.</p>
          <p>The Websites may include content provided by third parties, including materials provided by third-party licensors and aggregators. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by the Company, are solely the opinions and the responsibility of the person or entity providing those materials. Their materials do not necessarily reflect the opinion of the Company. We are not responsible or liable to you or any third party for the content or accuracy of any materials provided by any third party.</p>
          <h2>Information About You and Your Visits to the Websites</h2>
          <p>All information we collect on the Websites is subject to our Privacy Policy. By using the Websites, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.</p>
          <h2>Online Purchases and Other Terms and Conditions</h2>
          <p>All purchases through our site or other transactions for the sale of goods formed through the Websites, or resulting from visits to our Websites made by you, are governed by these Terms of Use.</p>
          <p>For protection of our brand, the products sold via the Websites are for personal use only. You are not permitted to resell products purchased on or through the Websites in a new or unused condition, whether on an individual basis or bundled with other products bearing the Company trademarks or brands. Unwanted new and otherwise resellable products may be returned where consistent with the Company’s return policy.</p>
          <p>Use of “drop-shipping”—including but not limited to allowing a third party to fulfill orders to customers on your behalf, and/or including listing products for sale on other platforms and using this Website as a fulfillment service for such listings—is strictly prohibited. We reserve the right to decline to fill orders believed to be placed for drop-shipping purposes. To the extent consistent with applicable law, violators of this policy may be restricted from future use of the Website.</p>
          <h2>Links from the Websites</h2>
          <p>If the Websites contains links to other sites and resources provided by third parties, these links are provided for your convenience only. We have no control over the contents of those sites or resources, and accept no responsibility for them, their content and/or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to our Websites, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.</p>
          <h2>Geographic Restrictions</h2>
          <p>We administer, control and operate the Websites from our offices in the State of Illinois, United States of America. The Websites are accessible world-wide. However, some of their features or functions may not be available or appropriate for use outside of the United States and/or may not be available to all persons or in all geographic locations. We make no representation that the Websites or our services and products are appropriate or authorized for use in all countries, states, provinces, counties, localities or any other jurisdictions. Your access and use of the Websites may not be legal in Your jurisdiction. If you choose to access, browse or use the Websites, you do so on your own initiative and at your own risk, and you are responsible for compliance with all applicable laws if, and to the full extent that, such laws and restrictions are applicable. Access to the Websites may not be legal by certain persons or in certain countries.</p>
          <p>The Site provides information of a general nature only. You are responsible for determining whether it applies to Your specific situation. We specifically disclaim any liability concerning any action that any individual may take based on any information or guidance provided at either Website.</p>
          <h2>Disclaimer of Warranties</h2>
          <p>You understand that we cannot and do not guarantee or warrant that the information and documentation contained on our Websites will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, OTHER ELECTRONIC DEVICES, PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITES OR ANY SERVICES OR PRODUCTS OBTAINED THROUGH THE WEBSITES OR TO YOUR DOWNLOADING OF ANY INFORMATION POSTED ON THEM, OR ON ANY WEBSITE LINKED TO THEM.</p>
          <p>THE WEBSITES, INCLUDING ALL SERVICES, CONTENT, FUNCTIONS AND MATERIALS, ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES WITH RESPECT TO ANY UPTIME OR UNINTERRUPTED ACCESS, THE AVAILABILITY, ACCURACY OR USEFULNESS OF ANY OR ALL CONTENT, OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT. WE DO NOT WARRANT THE WEBSITES OR THEIR CONTENTS AND/OR SERVICES WILL BE TIMELY, SECURE, UNINTERRUPTED, OR OPERATED FREE OF DELAYS IN TRANSMISSION, FAILURE IN PERFORMANCE, COMPUTER VIRUSES, INACCURACIES, ERRORS, OR DEFECTS. YOU USE THE WEBSITES AT YOUR OWN RISK. WE ALSO ASSUME NO RESPONSIBILITY, AND SHALL NOT BE LIABLE FOR ANY DAMAGES TO OR VIRUS(ES) THAT MAY INFECT ANY USER’S COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT OF ANY USER’S ACCESS TO, BROWSING, OR USE OF EITHER WEBSITE OR THE DOWNLOADING OF ANY CONTENT ON EITHER WEBSITE. USERS ARE SOLELY RESPONSIBLE FOR IMPLEMENTING SUFFICIENT PROCEDURES AND VIRUS CHECKS (INCLUDING ANTI-VIRUS, REGULAR SYSTEM UPGRADES AND OTHER SECURITY CHECKS AND MEASURES) TO SATISFY THEIR PARTICULAR REQUIREMENTS FOR THE ACCURACY AND SECURITY OF DATA INPUT AND OUTPUT. NO ADVICE, RESULTS OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY ANY USER FROM US OR THROUGH EITHER WEBSITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
          <p>TO THE FULLEST EXTENT PROVIDED BY LAW, THE COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</p>
          <p>THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
          <p>AS A USER, YOU ACKNOWLEDGE AND AGREE THAT YOUR SOLE REMEDY FOR ANY PROBLEMS OR DISSATISFACTION WITH THE SITE IS TO TERMINATE YOUR ACCOUNT AND DISCONTINUE ALL USE OF THE SITE.</p>
          <h2>Limitation on Liability</h2>
          <p>EXCEPT AS SET OUT BELOW, UNDER NO CIRCUMSTANCES, INCLUDING ANY BREACH OF CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE ARISING UNDER ANY OTHER LEGAL OR EQUITABLE THEORY WILL WE BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, EXEMPLARY, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES THAT ARISE OUT OF OR IN CONNECTION WITH THE USE OF OUR SITE OR INABILITY TO USE OUR SITE, OR FOR ANY SITE CONTENT, INFORMATION, SOFTWARE, PRODUCTS OR SERVICES OBTAINED OR ACCESSED THROUGH THE SITE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Some states or jurisdictions do not allow the exclusion or limitation of consequential or incidental damages and, in such states or jurisdictions, our liability shall be limited to the fullest extent permitted by law.</p>
          <p>IN NO EVENT SHALL WE BE LIABLE FOR ANY CONTENT POSTED, TRANSMITTED, EXCHANGED OR RECEIVED BY US OR ON BEHALF OF ANY USER ON OR THROUGH THE WEBSITES (INCLUDING ANY USER GENERATED SUBMISSIONS). IN NO EVENT SHALL OUR TOTAL LIABILITY TO ANY USER FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION EXCEED, IN THE AGGREGATE (i) THE AMOUNT, IF ANY, PAID BY THE USER TO US FOR HIS/HER/ITS USE OF THE SITE OR FOR ANY OF HIS/HER/ITS ACTIVITIES ON THE SITE DURING THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR (ii) NINE U.S. DOLLARS (USD$100.00), WHICHEVER IS GREATER.</p>
          <h2>Indemnification</h2>
          <p>You agree to defend, indemnify, and hold harmless the Company, its Affiliated Parties and our employees, contractors, agents, professional advisers, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debts, and expenses (including but not limited to actual attorney’s fees and costs) arising from: (i) your use of and access to the Websites, including any data or content transmitted, submitted, viewed, or received by you; (ii) your violation of any provision of these Terms of Use and/or Our Privacy Policy, including your breach of any of the representations and warranties contained in these Terms of Use; (iii) your violation of any third party right, including any right of privacy or intellectual property rights; (iv) your violation of any applicable law, rule or regulation; and/or (v) any other party’s access and use of the Websites and any of the Websites&apos; services or products with your unique username, password or other appropriate security code.</p>
          <h2>Termination</h2>
          <p>You may discontinue your use of our Websites at any time without informing us. We may, without prior notice, change the Websites and any of our services and products, stop providing them or any of their features to you or to users generally, or create usage limits for our Websites. We may permanently or temporarily terminate or suspend your access to our Websites without notice and without liability for any or no reason, including if, in our sole determination, you violate any provision of these Terms of User and/or our Privacy Policy. In particular, we may immediately terminate or suspend any Account that has been flagged for repeat infringement of any Marks or any other laws or Our Terms of Use and/or Privacy Policy.</p>
          <p>Upon termination of Your access to or ability to use our Websites, including but not limited to suspension of your account, your right to use or access any services or products will immediately cease. All provisions of these Terms of Use that by their nature should survive termination, shall survive termination, including, but not limited to, ownership provisions, warranty disclaimers, and limitations of liability. Termination of your access to and use of our Websites shall not relieve you of any obligations arising or accruing prior to such termination or limit any liability which you otherwise may have to us or any third party.</p>
          <h2>Release</h2>
          <p>To the fullest extent permitted by law, you release us, our Affiliated Parties and our related individuals, affiliates and subsidiaries, and any of their trustees, directors, officers, shareholders, employees, representatives, consultants, attorneys, agents, suppliers, distributors, licensees and/or licensors from any and all responsibility, liability, claims, demands, and/or damages (actual, statutory and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with the following: (i) disputes between users, including those between you and other users; (ii) third party sites and services, including content found on such sites and services; (iii) disputes concerning any use of or action taken using your access credential by you or a third party; (iv) claims relating to the unauthorized access to any data communications or content stored under or relating to your access credentials, including unauthorized use or alteration of such communications.</p>
          <p><strong>If You are an individual</strong> and have a dispute with one or more users of the Websites, or with any party who provides advertising or third party services, on or through either Website, or with any party who provides a website link to or on either Website or from third party content which is posted on the Websites, you release us and our Affiliated Parties from all claims, demands, and damages (incidental, indirect, punitive, statutory, exemplary, special or consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such dispute. If you have a dispute with any third party in any way pertaining to our Websites, services and/or products, you release us and our Affiliated Parties from any and all claims, demands, and damages (incidental, indirect, punitive, statutory, exemplary, special or consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such dispute. You also waive California Civil Code § 1542 which says:</p>
          <p>A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS THAT THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, AND THAT, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY.</p>
          <p>You also waive any and all benefits and rights that would otherwise accrue to you by reason of the provisions of any federal or state statute or principle of common law of any state of the United States, or any political entity or nation, province or local law or regulation that may govern this release, which statute, regulation, law or principle provides in substance something similar to California Civil Code § 1542. You agree not to file any action or lawsuit inconsistent with the foregoing release.</p>
          <h2>Dispute Resolution and Binding Arbitration.</h2>
          <p><strong>BY AGREEING TO BINDING ARBITRATION, YOU AND CARDS AGAINST HUMANITY ARE AGREEING TO GIVE UP ANY RIGHTS TO LITIGATE CLAIMS IN A COURT OR BEFORE A JURY, OR TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE ACTION WITH RESPECT TO A CLAIM. OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT MAY ALSO BE UNAVAILABLE OR MAY BE LIMITED IN ARBITRATION.</strong></p>
          <p><strong>ANY CLAIM, DISPUTE OR CONTROVERSY (WHETHER IN CONTRACT, TORT OR OTHERWISE, WHETHER PRE-EXISTING, PRESENT OR FUTURE, AND INCLUDING STATUTORY, CONSUMER PROTECTION, COMMON LAW, INTENTIONAL TORT, INJUNCTIVE AND EQUITABLE CLAIMS) BETWEEN YOU AND US ARISING FROM OR RELATING IN ANY WAY TO YOUR USE OF THE WEBSITES, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION.</strong></p>
          <p><strong>YOU AGREE THAT, BY AGREEING TO THESE TERMS, THE U.S. FEDERAL ARBITRATION ACT GOVERNS THE INTERPRETATION AND ENFORCEMENT OF THIS AGREEMENT, AND THAT YOU AND WE ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS OR PRIVATE ATTORNEY GENERAL ACTION.</strong> This arbitration provision shall survive termination of these Terms of Use.</p>
          <p>The arbitration will be administered by the American Arbitration Association (&quot;<strong>AAA</strong>&quot;) in accordance with its Consumer Arbitration Rules (the &quot;<strong>AAA Rules</strong>&quot;) then in effect, except as modified by this Section. (The AAA Rules are available at adr.org or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this section.</p>
          <p>The arbitrator will have exclusive authority to resolve any dispute relating to arbitrability and/or enforceability of this arbitration provision, including any unconscionability challenge or any other challenge that the arbitration provision or the Agreement is void, voidable or otherwise invalid. The arbitrator will be empowered to grant whatever relief would be available in court under law or in equity. Any award of the arbitrator(s) will be final and binding on each of the parties and may be entered as a judgment in any court of competent jurisdiction.</p>
          <p>Each party in an arbitration or small claims procedure will be responsible for their own legal fees.</p>
          <p>If permitted by local law, you may elect to pursue your claim in small-claims court rather than arbitration if you provide us with written notice of your intention do so within sixty (60) days of your purchase. The arbitration or small-claims court proceeding will be limited solely to your individual dispute or controversy.</p>
          <p>You agree to an arbitration on an individual basis. In any dispute, <strong>NEITHER YOU NOR CARDS AGAINST HUMANITY WILL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS BY OR AGAINST OTHER CUSTOMERS IN COURT OR IN ARBITRATION OR OTHERWISE PARTICIPATE IN ANY CLAIM AS A CLASS REPRESENTATIVE, CLASS MEMBER OR IN A PRIVATE ATTORNEY GENERAL CAPACITY</strong>. The arbitral tribunal may not consolidate more than one person&apos;s claims, and may not otherwise preside over any form of a representative or class proceeding. The arbitral tribunal has no power to consider the enforceability of this class arbitration waiver and any challenge to the class arbitration waiver may only be raised in a court of competent jurisdiction.</p>
          <p>Pre-Filing Mediation. In the event of a dispute, prior to initiating arbitration, the party asserting the claim must first send to the other, by overnight courier, a written Notice of Claim (“Notice”). If You are the claimant, the Notice to Us must be addressed to: Legal Department, Cards Against Humanity LLC, PO Box 316620, Chicago, IL 60631. Legal+Claims@cardsagainsthumanity.com. If We are the claimant, the Notice must be sent to the address We have on file for You in Your Account. The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought. Following receipt of the Notice, each party agrees to negotiate with the other in good faith about the claim. If the claim is not resolved to the satisfaction of the claimant within sixty (60) days after Notice is provided, the claimant may pursue the claim in arbitration or file a claim in small claims court, as appropriate.</p>
          <p>Settlement Offers: During the arbitration, the amount of any settlement offer made by You or Us shall not be disclosed to the arbitrator.</p>
          <p>Initiating A Claim: The form required to initiate an arbitration may be printed or downloaded from www.adr.org. Alternatively, You may contact the arbitration administrator by calling 1-800-778-7879 or writing to the American Arbitration Association, 150 N. Michigan Ave., Suite 3050, Chicago, Illinois, 60601.</p>
          <p>Location of Hearing: Unless you and we agree otherwise, any arbitration hearings will take place in Chicago, Illinois. If your claim is for US$10,000 or less, we agree you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic hearing, or by an in-person hearing as established by the AAA Rules. If your claim exceeds US$10,000, the right to a hearing will be determined by the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a written decision sufficient to explain the essential findings and conclusions on which the award is based.</p>
          <p><strong>Class/Private Attorney General Waivers: YOU AND WE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.</strong> Further, unless both you and we agree otherwise, the arbitrator may <strong>not</strong> consolidate the claims of more than one party, and may not otherwise preside over any form of a representative or class proceeding. If this specific provision is found to be unenforceable as applied to any claim asserted by any individual, then the entirety of the arbitration provision set forth herein shall be null and void.</p>
          <p>Injunctive Relief Limitation: The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide the relief warranted by that party’s individual claim.</p>
          <p>Small Claims Procedure Alternative: Notwithstanding the foregoing binding arbitration procedure, either party may bring an individual action in small claims court (provided the claim otherwise qualifies for such a program) as an alternative to proceeding with arbitration.</p>
          <h2>Opt-Out Provision</h2>
          <p>You may elect to opt out (exclude yourself) from the final, binding arbitration procedure and the class and private attorney general action waivers specified in these Terms of Use by doing the following. Within 15 days of your first accessing either Website, you must send a letter to us at Cards Against Humanity, LLC, PO Box 316620, Chicago, IL 60631, that specifies Your (1) name, (2) IP address(es), (3) mailing address, and (4) request to be excluded from the final, binding arbitration procedure and class/private attorney general action waivers specified in these Terms of Use. All other Terms of Use shall continue to apply to you, including the requirement to participate in pre-dispute mediation. You are not required to send the letter by certified mail, return receipt requested or overnight courier, but it is recommended that you do so. Your request to be excluded will only be effective and enforceable if you can prove the request was postmarked within the applicable 15-day deadline.</p>
          <h2>Notice for California Users</h2>
          <p>Under California Civil Code Section 1789.3, users of the Websites from California are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 400 R Street, Suite 1080, Sacramento, California 95814, or by telephone at (916) 445-1254 or (800) 952-5210.</p>
          <h2>Notice For New Jersey Users</h2>
          <p>The following sections shall not apply to users of the Websites from New Jersey: Disclaimers/No Warranties, Limitation of Liability and Jurisdiction.</p>
          <h2>Limitation on Time to File Claims</h2>
          <p>ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE, OUR PRIVACY POLICY, AND/OR THE WEBSITES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY TIME BARRED.</p>
          <h2>Jurisdiction</h2>
          <p>If any court of competent jurisdiction finds the above arbitration and/or class action waiver provisions invalid or inapplicable, you agree to the exclusive jurisdiction of the federal and state courts located in Chicago, Illinois, and the related appellate courts, in any related action or proceeding. Further, you irrevocably submit to the exclusive jurisdiction of, and venue in, the state and federal courts in Chicago, Illinois, and the related appellate courts, in any related action or proceeding and agree shall to not raise any claims as to Chicago, Illinois being an inconvenient forum.</p>
          <h2>Governing Laws</h2>
          <p>You agree the laws of the United States of America and the laws of the State of Illinois, without regard to any principles of conflicts of laws, will govern these Terms of Use, our Privacy Policy, your use of the Websites, and all matters relating to your access to, and/or use of, the Websites, including all disputes between you and us. You also agree that: (i) the Websites shall be deemed solely based in Illinois; and (ii) the Websites shall be passive sites that do not give rise to personal jurisdiction over us, either specific or general, in any jurisdiction other than Illinois.</p>
          <h2>Waiver and Severability</h2>
          <p>No waiver by the Company of any term or condition set out in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
          <p>If any part of these Terms of Use is determined to be invalid or unenforceable under applicable law, including the warranty disclaimers and liability limitations stated elsewhere herein, then the invalid or unenforceable provision(s) will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision, and the remainder of these Terms of Use shall continue in full effect.</p>
          <h2>Entire Agreement</h2>
          <p>The Terms of Use and our Privacy Policy constitute the sole and entire agreement between you and Cards Against Humanity regarding the Websites and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, whether electronic, written or oral, regarding the Websites, our services and our products.</p>
          <p>These Terms of Use shall be deemed to include all other notices, policies, disclaimers and other terms and conditions contained in or on the Websites, including Our Privacy Policy; provided, however, these Terms of Use shall prevail in the event of a conflict with any such other documents. Any rights not expressly granted in these Terms of Use are reserved to us.</p>
          <p>A printed version of these Terms of Use and of any notice given in electronic form shall be admissible in any and all judicial or administrative proceedings based upon or relating to these Terms of Use to the same extent as other business documents and records originally generated and maintained in printed form.</p>
          <h2>Miscellaneous</h2>
          <p>These Terms of Use constitute the entire agreement between you and us and govern your use of the Websites and our services and product.</p>
          <p>These Terms and the rights, benefits and obligations contained herein are fully assignable by us and will be binding upon and inure to the benefit of our successors and assigns.</p>
          <p>No party, nor any of the parties’ respective attorneys, shall be deemed the drafter of this agreement for purposes of interpreting any provision hereof in any judicial or other proceeding that may arise between the parties.</p>
          <p>Except as otherwise expressly provided in these Terms of Use, there shall be no third party beneficiaries to this agreement. For the purpose of clarity, our Affiliated Parties, and other representatives, affiliates and subsidiaries, and any of their trustees, directors, officers, shareholders, employees, representatives, consultants, attorneys, agents, suppliers, distributors, licensees or licensors are intended to be and are considered third party beneficiaries of this agreement.</p>
          <p>We may terminate these Terms of Use for any or no reason at any time by notifying you through a notice on the Websites or by any other method of communication provided elsewhere herein. Any such termination will be without prejudice to our rights, remedies, claims, or defenses hereunder.</p>
          <h2>Your Comments and Concerns</h2>
          <p>The Websites are operated by Cards Against Humanity, PO Box 316620, Chicago, IL 60631.</p>
          <p>All other feedback, comments, requests for technical support, and other communications relating to the Websites should be directed to: mail@cardsagainsthumanity.com.</p>
          <h2>Privacy Policy</h2>
          <p>We at Cards Against Humanity (<strong>“Company”</strong>, <strong>“Us”</strong> or <strong>“We”</strong>) respect your privacy and are committed to protecting it through our compliance with this policy.</p>
          <p>This Privacy Policy describes the types of information we may collect from you or that you may provide when you visit our websites, as well as our practices for collecting, using, maintaining, protecting, and disclosing that information.</p>
          <p>Cards Against Humanity and its Affiliated Entities (as defined below) collectively own, operate, and maintain cardsagainsthumanity.com, store.cardsagainsthumanity.com, and yowza.social (our “<strong>Websites</strong>”) and all of the various pages contained therein, including subdomains, and the related products and services, whether provided through a website owned, maintained, or controlled by us, through a social network, a mobile application, on a cellular telephone, or otherwise.</p>
          <p>This Privacy Policy (“Policy”) is an agreement between You and Us. It is governed by and incorporated by reference into the Terms of Use, and should be interpreted consistent therewith.</p>
          <p>Cards Against Humanity includes Cards Against Humanity, LLC and its trustees, directors, officers, shareholders, members, employees, contractors, advisors, representatives, subcontractors, consultants, attorneys, agents, suppliers, distributors, licensees and licensors (current and past), and any affiliates, individually and collectively, and any related individuals or entities. Affiliated Parties means Cards Against Humanity, LLC and any related individuals, affiliates, and subsidiaries, and any of their trustees, directors, officers, shareholders, members, employees, representatives, consultants, attorneys, agents, suppliers, distributors, licensees, and/or licensors.</p>
          <p>Cards Against Humanity provides the Websites to you subject to the following Policy, which you acknowledge, agree to, and consent to by using the Websites.</p>
          <p>This Policy applies to information we collect:</p>
          <ul>
            <li>On the Websites.</li>
            <li>In e-mail, text, and other electronic messages between you and the Websites.</li>
            <li>When you interact with our advertising on third-party websites and services, if the advertising includes links to this policy.</li>
          </ul>
          <p>It does not apply to information collected by:</p>
          <ul>
            <li>Us offline; or</li>
            <li>Any third party (including our affiliates and subsidiaries), including through any application or content (including advertising) that may link to or be accessible from the Websites.</li>
          </ul>
          <p><strong>PLEASE READ THIS POLICY CAREFULLY TO UNDERSTAND OUR POLICIES AND PRACTICES REGARDING YOUR INFORMATION AND HOW WE WILL TREAT IT. IF YOU DO NOT AGREE WITH OUR POLICIES AND PRACTICES, YOUR CHOICE IS NOT TO USE OUR WEBSITE. BY ACCESSING OR USING THIS WEBSITE, YOU INDICATE YOU HAVE READ AND UNDERSTOOD THIS PRIVACY POLICY AND AGREE TO ITS PROVISIONS. THIS POLICY MAY CHANGE FROM TIME TO TIME. YOUR CONTINUED USE OF THIS WEBSITE AFTER WE MAKE CHANGES IS DEEMED TO BE ACCEPTANCE OF THOSE CHANGES, SO PLEASE PERIODICALLY CHECK THIS POLICY FOR ANY UPDATES.</strong></p>
          <p>You also represent that you are at least 13 years old and not a person barred from receiving services under the laws of the United States or other applicable jurisdictions.</p>
          <p><strong>1.</strong> <strong>California Residents</strong></p>
          <p>If you are a California resident and are under 18 years of age, you may request and obtain removal of postings on the Websites that you yourself post by e-mailing us at privacy@cardsagainsthumanity.com. All requests must be labeled &quot;California Removal Request&quot; on the e-mail subject line. All requests must provide a description of the content or information in your posting that you want removed and information reasonably sufficient to permit us to locate the material, and include the name and URL (if applicable) of the website, application, or other interactive service. We shall not accept requests via postal mail, telephone, or facsimile.</p>
          <p><strong>2.</strong> <strong>Children’s Privacy</strong></p>
          <p>By using our Websites, you represent that you are at least 13 years old. The Websites are not directed toward children under 13 years of age, nor do we knowingly collect information about children under 13. If you are under 13 years of age, you are not permitted to submit any personally identifiable information (“PII”) to us, including your name, address, telephone number, e-mail address, or any screen name or user name you may use. If we learn we have collected or received PII from a child under 13 without verification of parental consent, we will delete it immediately. If a parent or guardian becomes aware that any of their children has submitted PII to us, please immediately notify us at privacy@cardsagainsthumanity.com.</p>
          <p><strong>3.</strong> <strong>Information We Collect About You and How We Collect It</strong></p>
          <p>We collect several types of information from and about users of our Websites:</p>
          <p><strong>Identifiers:</strong> We may collect your e-mail, real name, nickname, e-mail address, telephone number; and date of birth, country of birth, and state of birth (if in the U.S.) to identify you and for research purposes to make our products better and to effectuate Webstore sales. This information is collected directly from you during your registration with our Websites. We do not sell or share this information with any third party.</p>
          <p><strong>Personal information categories listed in the California Customer Records statute (Cal. Civ. Code § 1798.80(e)):</strong> We collect your name, address, and education to identify you and for gameplay analytics purposes. This information is collected directly from you during your registration with our Websites. We do not sell or share this information with any third party.</p>
          <p><strong>Protected classification characteristics and sensitive personal information:</strong> We collect information about your race/ethnicity, religion or creed, sex, sexual orientation (including gender, gender identity, and gender expression) and political views for gameplay analytics purposes. This information is collected directly from you during your registration with our Services. We do not sell or share this information with any third party.</p>
          <p><strong>Commercial Information:</strong> We collect purchaser e-mail and payment method, for internal reporting and billing. This information is collected from you and automatically during your interaction with our Websites. We do not sell or share this information with any third party.</p>
          <p><strong>Internet or other similar network activity:</strong> When you use our Websites we may collect and store your Internet Protocol address, browser, device type, and device operation system for compatibility, tech support, and analytics. We do not sell or share this information with any third party.</p>
          <p>“Share” or “sell” means the sale of your personal information to an outside party for monetary or other valuable consideration, subject to certain exceptions as provided by the applicable privacy laws. We do not sell or share your information for monetary consideration. However, we may share information that we collect in the Lab (lab.cardsagainsthumanity.com) with academic researchers. For more information please see Section 5 (Disclosure of Your Information).</p>
          <p>We collect this information:</p>
          <ul>
            <li>Directly from you when you provide it to us.</li>
            <li>Automatically as you navigate through the site. Information collected automatically may include usage details, IP addresses, and information collected through cookies.</li>
          </ul>
          <p><strong>Information You Provide to Us</strong></p>
          <p>The information we collect on or through our Websites may include:</p>
          <ul>
            <li>Information that you provide by filling in forms on our Websites. This includes information you provide at the time of setting up an account and/or making a purchase. We may also ask you for information when you enter a contest or promotion sponsored by us, and when you report a problem with our Websites or express concerns about our products.</li>
            <li>Records and copies of your correspondence (including e-mail addresses), if you contact us.</li>
            <li>Details of transactions you carry out through our Websites and of the fulfillment of your orders. You may be required to provide financial information before placing an order through our Websites.</li>
            <li>Your search queries on the Websites.</li>
          </ul>
          <p><strong>Information We Collect Through Automatic Data Collection Technologies</strong></p>
          <p>As you navigate through and interact with our Websites, we may use automatic data-collection technologies to collect certain information about your equipment, browsing actions, and patterns, including:</p>
          <ul>
            <li>Details of your visits to our Websites, including traffic data, location data, logs, and other communication data and the resources that you access and use on the Website.</li>
            <li>Information about your computer and internet connection, including your IP address, operating system, and browser type.</li>
          </ul>
          <p>Some browsers have a “do not track” feature that lets you tell those websites you do not want to have your online activities tracked. At this time, we do not respond to browser “do not track” signals. Except as described below, no other third party conducts tracking or analytics on our site.</p>
          <p>You may not find third-party website links on all of the pages of our Websites. However, where they are provided, this Privacy Policy does not cover the information privacy practices of any of those third-party websites or those you may otherwise be able to access from our Website. We do not control, and are not responsible for, any such third-party websites&apos; collection and use of your information. All users should timely refer to the privacy policy disclosures on those websites to obtain information regarding their information collection and use practices.</p>
          <p>The information we collect automatically does not include PII, but we may maintain or associate that information with PII we collect in other ways. Doing so helps us to improve our Websites and to deliver a better and more personalized service, including by enabling us to:</p>
          <ul>
            <li>Estimate our audience size and usage patterns.</li>
            <li>Store information about your preferences, allowing us to customize our Websites according to your individual interests.</li>
            <li>Recognize you when you return to our Websites.</li>
          </ul>
          <p>The technologies we use for this automatic data collection may include “cookies.” Cookies are files with small amounts of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your computer’s hard drive. Like many sites, we use “cookies” to recognize your logged-in state on our website, to understand what Services you are interested in, to make our Websites function for you, and to help your browsing experience and use of the Websites and our Services feel more customized. You may be able to instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Websites. You can obtain more information about cookies at <a href='http://www.allaboutcookies.org/'>http://www.allaboutcookies.org/</a>.</p>
          <p>We may also use web beacons, pixel tags, and similar software, which are invisible graphics on a web page or e-mail that are programmed to collect non-PII about the use of a given website or newsletter, such as whether or not an e-mail is opened and viewed.</p>
          <p>We use the following Google Analytics Advertising Features:</p>
          <ul>
            <li>Google Display Network Impression Reporting.</li>
            <li>Integrated services that require Google Analytics to collect data via advertising cookies and anonymous identifiers.</li>
          </ul>
          <p>You can opt-out of the Google Analytics Advertising Features here: <a href='https://tools.google.com/dlpage/gaoptout/'>https://tools.google.com/dlpage/gaoptout/</a>. You can also opt-out through any other available means.</p>
          <p>You can read more at the Google Analytics Privacy Overview: <a href='https://policies.google.com/technologies/partner-sites'>https://policies.google.com/technologies/partner-sites</a></p>
          <p><strong>Third-Party Use of Cookies and Other Tracking Technologies</strong></p>
          <p>Some content or applications, including advertisements, on the Websites are served by third parties, including advertisers, ad networks and servers, content providers, and application providers. These third parties may use cookies alone or in conjunction with web beacons or other tracking technologies to collect information about you when you use our Websites. The information they collect may be associated with your personal information or they may collect information, including personal information, about your online activities over time and across different websites and other online services. They may use this information to provide you with interest-based (behavioral) advertising or other targeted content.</p>
          <p>We do not control these third parties&apos; tracking technologies nor how they may be used. If you have any questions about an advertisement or other targeted content, you should contact the responsible provider directly.</p>
          <p><strong>4.</strong> <strong>How We Use Your Information</strong></p>
          <p>We use the information we collect about you or that you provide to us, including any PII:</p>
          <ul>
            <li>To present our Websites and their contents to you.</li>
            <li>To provide the products and services you request.</li>
            <li>To deliver and track shipments.</li>
            <li>To provide customer support, and respond to your requests, questions, and comments pertaining to your purchase.</li>
            <li>To process returns and refunds.</li>
            <li>To perform data analyses (including geographic distribution of shipments, or financial analysis).</li>
            <li>To conduct research and analysis to improve our products.</li>
            <li>To protect against, identify, and prevent fraud and other criminal activity.</li>
            <li>To comply with applicable legal requirements.</li>
            <li>To fulfill any other purpose for which you provide the information.</li>
            <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</li>
            <li>To notify you about changes to our Websites or any products or services we offer or provide through it.</li>
            <li>In any other way we may describe when you provide the information.</li>
            <li>For any other purpose with your consent.</li>
          </ul>
          <p>Cards Against Humanity will retain your information only for as long as is necessary for the purposes set out in this Privacy Policy, or as needed to provide the services to you or otherwise to satisfy our legitimate business interests. Cards Against Humanity will retain and use your information to the extent necessary to comply with our legal obligations (for example, if we are required to retain your information to comply with applicable tax/revenue laws), resolve disputes, enforce our agreements, and as otherwise described in this Privacy Policy.</p>
          <p><strong>5.</strong> <strong>Disclosure of Your Information</strong></p>
          <p>We may disclose aggregated information about our users, and information that does not identify any individual, without restriction.</p>
          <p>Cards Against Humanity will not sell, share, dispose, or otherwise transfer your PII to third parties without your consent except as specifically set forth in this Privacy Policy. When you choose to supply us with your e-mail address, Cards Against Humanity compiles this information in a database with other Cards Against Humanity customer information.</p>
          <p>We may disclose PII that we have about you as described in this Privacy Policy:</p>
          <ul>
            <li>To our subsidiaries and affiliates.</li>
            <li>To contractors, service providers, and other third parties we use to support our business (e.g., payment processors and courier services) and who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which we disclose it to them.</li>
            <li>To a buyer or other successor in interest in the event of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Cards Against Humanity’s assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which PII held by Cards Against Humanity about our Websites’ users is among the assets transferred.</li>
            <li>To fulfill the purpose for which you provide the information.</li>
            <li>For any other purpose disclosed by us when you provide the information.</li>
            <li>With your consent.</li>
          </ul>
          <p>We may also disclose your personal information:</p>
          <ul>
            <li>To enforce our Terms of Use and this Privacy Policy, including any investigation of potential violations thereof;</li>
            <li>To notify you about any changes in or to our Websites or other products or services;</li>
            <li>To fulfill our legal obligations or to otherwise contact you;</li>
            <li>To fulfill our legal obligations and respond to any claims, litigation and/or law enforcement or other government inquiry;</li>
            <li>To deliver products and services to you and to improve the design and performance of the Websites. We may also use your information to deliver to you, among other things, communications, e-mails, and marketing materials from us and third parties as you request them or which we feel may interest you, where you have consented to be contacted for such purposes;</li>
            <li>To ensure that our Websites, products, and services are presented to you in the most efficient manner for you and us and to improve the design and performance of the Websites;</li>
            <li>To administer our Websites and keep them safe and secure, and for internal operations, including research, statistics, troubleshooting, detection/prevention/addressing any potential credit risks/fraud prevention, data analysis, testing, security, survey, and similar purposes;</li>
            <li>To share the data we hold with third-party service providers, including credit card processors, auditors, other service providers, and academic researchers for industry research and development, demographic profiling, and other similar purposes;</li>
            <li>To disclose as we believe to be necessary or appropriate: (a) under applicable law, including laws outside your country of residence; (b) to protect our operations or those of any of our Affiliated Parties; (c) to protect our rights, privacy, safety, or property, or that belongs to you or others; or (d) to allow us to pursue available remedies or limit the damages that we may sustain; and/or</li>
            <li>For any other legitimate business purpose we may have in accord with this Privacy Policy, including but not limited to protection of our rights, property, or safety, or the rights, property, and safety of our employees, users and/or others.</li>
          </ul>
          <p>You must notify us immediately of any suspected or actual unauthorized use of your customer information, and of any and all other security breaches.</p>
          <p><strong>6.</strong> <strong>Choices About How We Use and Disclose Your Information</strong></p>
          <p><strong>Opting Out of Cross-Context Behavioral Advertising or “Sales” of your Information.</strong></p>
          <p>Under the laws of certain U.S. states, you may have the right to opt out of our processing or sharing of your information for online cross-context behavioral advertising purposes. Note that certain state laws also allow you to opt out of the “sale” of your information to third parties in exchange for valuable consideration.</p>
          <p><strong>Communications Preferences.</strong></p>
          <p>We strive to provide you with choices regarding the PII you provide to us. You have the right to ask us not to process your personal data for marketing purposes. If you have signed up for our e-mail list and later decide you don’t want to receive any more e-mails from us, you have the choice at any time to withdraw your consent for us to contact you by using the “unsubscribe” function in our e-mail messages, or by contacting us via e-mail at privacy@cardsagainsthumanity.com, or by postal mail at: Cards Against Humanity Customer Service, PO Box 316620, Chicago, IL, 60631, USA.</p>
          <p>You also have the choice to do the following at any time by contacting us via the e-mail or postal address above:</p>
          <p><strong>Your rights</strong>. The California Consumer Privacy Act of 2018 (“CCPA”), as amended by the California Privacy Rights Act of 2020, effective January 1, 2023 (“CPRA”) and some other state privacy laws provide consumers with specific rights regarding their personal information. This section describes your rights and explains how to exercise those rights.</p>
          <p>1. <strong>Right To Know What Information We Collect, With Whom We Share Your Information, And The Right To Data Portability:</strong> You may request that we disclose to you the categories of personal information we collect about you, the categories of sources from which we collected that personal information, the categories of personal information we sold or disclosed, our business or commercial purposes for collecting and selling such personal information, the categories of third parties with whom we shared such personal information, and the specific pieces of personal information we collected about you over the past 12 months.</p>
          <p>2. <strong>Right To Request Deletion Of Your Information:</strong> You may request we delete some or all of the personal information we maintain about you, subject to certain exceptions. If we cannot delete your personal information, we will give you a reason why we cannot do so. For security reasons, you or your authorized agent may be asked to verify your/their identity. Note that some personal data may be retained as permitted by law (e.g., to comply with legal obligations, to prevent fraud). We will delete or deidentify personal information not subject to certain exceptions from our records and will direct our service providers to take similar action.</p>
          <p>3. <strong>Opt-out of “Sale”/“Sharing” of your personal information:</strong> We do not currently consider the ways we shared consumer personal information in the past 12 months to comprise the “sale” of personal information as defined in the CCPA or other applicable state privacy laws. For purposes of this Privacy Policy, “sell” means the sale of your personal information to an outside party for monetary or other valuable consideration, subject to certain exceptions in the CCPA or other applicable privacy laws.</p>
          <p>4. <strong>Right to Correct Inaccurate Personal Information:</strong> Taking into account the nature of the personal information and the purposes of the processing, this right provides an individual with the ability to seek to correct or update personal data that individual considers that we hold about that individual.</p>
          <p>5. <strong>Right to Limit Use of Sensitive Information:</strong> This right is limited to sensitive personal information used for the purpose of inferring characteristics about an individual. We do not collect sensitive personal information nor do we use sensitive personal information for the purpose of inferring characteristics about an individual, therefore we do not offer a path to exercise this right.</p>
          <p>6. <strong>Right of Non-Discrimination and Non-Retaliation:</strong> This right prohibits (a) denying an individual access to or use of goods and services, (b) charging different prices or rates for those goods and services, and/or (c) providing a different level or quality of those goods or services, as a result of the individual exercising any right under any data protection and privacy laws and/or regulations. We will not discriminate against you because you made any of these requests. We will not: (i) deny you goods or services; (ii) charge you different prices or rates for those goods or services, including through granting discounts or other benefits, or imposing penalties; (iii) provide you a different level or quality of our goods or services, or (iv) suggest that you may receive a different price or rate for our goods or services or a different level or quality of our goods or services.</p>
          <p>In addition to the rights that are available to residents of California, other state privacy laws may guarantee the rights to:</p>
          <ul>
            <li>Opt out of the processing of your personal data for the purposes of targeted advertising and for profiling in furtherance of decisions—including, for residents of Connecticut, solely automated decisions—that produce legal or similarly significant effects; and</li>
            <li>Appeal any decision or indecision related to the exercise of any right the consumer is granted under the applicable state law.</li>
          </ul>
          <p>If you would like to exercise any of these rights (including the right to appeal), please contact us by e-mailing us at: privacy@cardsagainsthumanity.com, or via postal mail at PO Box 316620, Chicago, IL 60631, or via phone at (800) 942-4410.</p>
          <p>We may deny certain requests, or fulfill a request only in part, based on our legal rights and obligations. For example, we may retain personal information as permitted by law, such as for tax or other record keeping purposes, to maintain an active account, to process transactions and facilitate customer requests, and/or to protect against fraud and other misuse of our Websites. We will take reasonable steps to verify your identity prior to responding to certain of your requests. The verification steps will vary depending on the sensitivity of the personal information. In some locations, you may designate an authorized agent to make a request on your behalf. When submitting such a request, please ensure you have adequately identified and authorized anyone acting on your behalf.</p>
          <p><strong>Shine the Light.</strong> California&apos;s “Shine the Light” law (Civil Code Section § 1798.83) permits users of our App who are California residents to request certain information regarding our disclosure of personal information to third parties for their direct marketing purposes. To make such a request, please send an e-mail to privacy@cardsagainsthumanity.com or write us at: Cards Against Humanity Legal Department, PO Box 316620, Chicago, IL 60631.</p>
          <p><strong>Response Timing and Format.</strong> We will confirm receipt of your request to know, correct, delete, and/or seek any request under the relevant U.S. state privacy law(s) within ten (10) business days. If you do not receive confirmation within the 10-day timeframe, please contact us at privacy@cardsagainsthumanity.com. We endeavor to substantively respond to a verifiable consumer request within forty-five (45) days of receipt. If we require more time (up to another 45 days), we will timely inform you of the reason(s) and extension period in writing. We may choose to verify your identity before responding to any such request.</p>
          <p>Any disclosures we provide will only cover the 12-month period preceding our receipt of your request. The response we provide will also explain the reasons we cannot comply with a request, if applicable. For data portability requests, we will select a format to provide your personal information that is readily usable and should allow you to transmit the information from one entity to another entity without hindrance.</p>
          <p><strong>7.</strong> <strong>Data Security and Storage</strong></p>
          <p>We store your information primarily in the United States. Some information may be stored elsewhere. You authorize us to do so. The PII and other data we collect about you and your use of our Websites may be maintained in servers we control and maintain or in third-party servers. The information you provide may be transferred or accessed by entities in many different countries as described elsewhere in this Policy. By submitting your information, you agree to the transfer, storage, and processing of your data in accord with this Policy.</p>
          <p>We have technical, administrative, and physical safeguards in place to help protect against unauthorized access to, use, and disclosure of PII and other information we maintain. Access to this information is authorized only for those who have a business need for such access.</p>
          <p>We will do our best to keep the PII data we maintain secure. However, no program is totally secure. Therefore, we cannot guarantee that our safeguards will prevent every attempt at unauthorized access or use, or the disclosure of any PII. If you become aware of a security breach, please notify us immediately at privacy@cardsagainsthumanity.com.</p>
          <p><strong>8.</strong> <strong>Payment</strong></p>
          <p>Cards Against Humanity does not store credit-card data. Customer encrypted credit-card data is securely stored and processed by our payment-processing vendor. For more details on how credit card information is handled/secured by our payment-processor vendor, please see Stripe’s Privacy Policy: <a href='https://stripe.com/us/privacy'>https://stripe.com/us/privacy</a>.</p>
          <p><strong>9.</strong> <strong>Laws in Other Countries</strong></p>
          <p>We comply with United States privacy laws and regulations. We do not represent our Websites are governed by, or operated in accordance with, the laws of other nations or jurisdictions, or that the Websites or any portion of them are appropriate or available for use in any particular location. If you choose to access our Websites, you do so at your own risk, and you are responsible for complying with all local laws, rules, and regulations. By using the Websites, visitors to the Websites from outside the United States acknowledge and agree that our Websites are subject to United States laws and regulations, and waive any claims against us that may arise under their own national laws.</p>
          <p><strong>10.</strong> <strong>Vermont Residents</strong></p>
          <p>The information practices described above comply with U.S. federal law. Vermont law places additional limits on the sharing of your PII. In accordance with Vermont law, we will not disclose information we collect about Vermont residents to unaffiliated companies except as permitted by law, such as with the authorization or consent of the Vermont resident.</p>
          <p><strong>11.</strong> <strong>Changes to Our Privacy Policy</strong></p>
          <p>We reserve the right to modify this Privacy Policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the Websites. If we make material changes to this policy, we will notify you that it has been updated via an announcement on our Websites, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it.</p>
          <p>In case there is a conflict between the terms established in this Privacy Policy and the terms established in our Terms of Use, the Terms of Use prevail.</p>
          <p><strong>12.</strong> <strong>Contact Information</strong></p>
          <p>To ask questions or comment about this Privacy Policy and our privacy practices, contact us at privacy@cardsagainsthumanity.com or by mail to: Cards Against Humanity Legal Department, PO Box 316620, Chicago, IL 60631 USA.</p>
          <p><strong>Website</strong>: www.cardsagainsthumanity.com</p>
          <p>If you need to access this Privacy Policy in an alternative format due to having a disability, please contact privacy@cardsagainsthumanity.com or (800) 942-4410.</p>
        </div>

        <Helmet>
          <title>{intl.formatMessage(messages.title)}</title>
          <meta name='robots' content='all' />
        </Helmet>
      </Column>
    );
  }

}

export default injectIntl(PrivacyPolicy);
