part_one:
  - coool
  - yowza
  - tasty
  - goood
  - juicy
  - brown
  - toady
  - mushy
  - hasty
  - weird
  - yucky
  - poopy
  - firey
  - greek
  - toxic
  - saucy
  - older
  - quick
  - spacy
  - noooo
  - alpha
  - weedy
  - super
  - magic
  - funky
  - vivid
  - swell
  - royal
  - moldy
  - empty
  - janky
  - built
  - angry
  - tacky
  - furry
  - right
  - light
  - large
  - boggy
  - porky
  - novel
  - kissy
  - crazy
  - corny
  - plain
  - swole
  - rowdy
  - giant
  - turbo
  - whole
  - heavy
  - broke
  - peppy
  - kinky
  - agile
  - godly
  - dense
  - lanky
  - happy
  - loose
  - tired
  - viral
  - burly
  - fifty
  - power
  - prime
  - hairy
  - enjoy
  - hunky
  - lucky
  - clean
  - shiny
  - handy
  - soggy
  - bossy
  - merry
  - legit
  - local
  - jolly
  - milky
  - tangy
  - dazed
  - grand
  - great
  - fancy
  - chill
  - husky
  - vegan
  - worst
  - rigid
  - meaty
  - beefy
  - valid
  - fussy
  - sweet
  - leafy
  - minty
  - boney
  - ratty
  - papal
  - daily
  - doing
  - smoky
  - rough
  - silly
  - nerdy
  - whack
  - soapy
  - goopy
  - ooooo
  - oiled
  - quiet
  - slick
  - blunt
  - picky
  - risky
  - solid
  - burny
  - chewy
  - jazzy
  - alive
  - grown
  - safer
  - awful
  - shady
  - vague
  - baggy
  - inane
  - pasty
  - rapid
  - rival
  - soppy
  - iowan
  - basic
  - chief
  - farmy
  - bleak
  - soupy
  - cushy
  - frail
  - pudgy
  - wacky
  - musty
  - bored
  - funny
  - proud
  - gaunt
  - boaty
  - major
  - elder
  - eerie
  - hefty
  - humid
  - fetid
  - jumbo
  - elite
  - ohian
  - daffy
  - dandy
  - gunky
  - spent
  - gummy
  - indie
  - leaky
  - malty
  - batty
  - noble
  - pithy
  - pious
  - pulpy
  - sandy
  - rusty
  - mealy
  - tipsy
  - plump
part_two:
  - fresh
  - yowza
  - fried
  - burro
  - winky
  - femme
  - sewer
  - frown
  - polar
  - clock
  - ramen
  - flame
  - derpy
  - covid
  - agave
  - messy
  - stone
  - grunt
  - chili
  - bundt
  - texas
  - curry
  - gloom
  - jelly
  - space
  - fishy
  - swank
  - fluid
  - truck
  - lunch
  - bidet
  - nacho
  - bread
  - macho
  - norse
  - moist
  - whomp
  - trash
  - weepy
  - chest
  - fiber
  - biden
  - prize
  - piano
  - punch
  - scary
  - water
  - grass
  - uncle
  - money
  - phone
  - foody
  - human
  - dance
  - slush
  - manly
  - train
  - movie
  - gross
  - ocean
  - drool
  - sugar
  - lumpy
  - spicy
  - steel
  - knife
  - yacht
  - laser
  - canoe
  - gassy
  - boxer
  - metal
  - trust
  - strut
  - cigar
  - tater
  - thump
  - ghoul
  - ghost
  - santa
  - buddy
  - bible
  - demon
  - angel
  - purge
  - ninja
  - roast
  - field
  - warty
  - floor
  - dream
  - pagan
  - slurp
  - kebab
  - mummy
  - opium
  - stink
  - stank
  - manga
  - cyber
  - devil
  - onion
  - clown
  - belly
  - spice
  - anime
  - gravy
  - beach
  - squid
  - virus
  - hydro
  - smile
  - nixon
  - tweed
  - zombo
  - chonk
  - tiger
  - steam
  - stoop
  - pasta
  - tooth
  - pants
  - sushi
  - carbo
  - snort
  - witch
  - nylon
  - chump
  - couch
  - beast
  - mulch
  - caper
  - goose
  - stomp
  - gator
  - prawn
  - bagel
  - robot
  - vapor
  - pizza
  - elven
  - stump
  - shock
  - bacon
  - mango
  - puppy
  - tummy
  - fruit
  - moose
  - rhino
  - porch
  - camel
  - bongo
  - crush
  - mondo
  - thigh
  - froyo
  - baked
  - clove
  - idaho
  - disco
  - gamer
  - towel
  - latex
  - macro
  - melty
  - navel
  - night
  - vodka
  - potty
  - speed
  - loner
  - spear
  - trout
  - stick
part_three:
  - frogs
  - yowza
  - boing
  - house
  - world
  - dunks
  - drugs
  - lords
  - cakes
  - pilaf
  - tires
  - baker
  - tryst
  - leper
  - spray
  - crabs
  - boots
  - mercy
  - butts
  - plane
  - holes
  - farts
  - goops
  - spell
  - dudes
  - quack
  - voter
  - blaze
  - piles
  - pills
  - dumps
  - video
  - tanks
  - smell
  - gnome
  - chunk
  - lumps
  - chugs
  - bears
  - thumb
  - memes
  - caves
  - lands
  - candy
  - clams
  - feast
  - liker
  - debut
  - times
  - place
  - homes
  - spoon
  - films
  - bunch
  - tumor
  - party
  - faces
  - crypt
  - drink
  - flesh
  - ducks
  - hunks
  - gulch
  - blimp
  - salad
  - eagle
  - toast
  - award
  - tweet
  - whale
  - rager
  - plums
  - joint
  - sweat
  - shark
  - gloop
  - union
  - slime
  - arena
  - event
  - verse
  - drums
  - tuber
  - bloke
  - fears
  - horse
  - ditch
  - chaos
  - melon
  - sloth
  - ranch
  - bucks
  - barge
  - tears
  - farms
  - poops
  - knees
  - games
  - cream
  - mouth
  - error
  - trick
  - males
  - fakes
  - armor
  - today
  - meats
  - jesus
  - bunny
  - clips
  - haver
  - kinks
  - toons
  - eater
  - liars
  - globs
  - hawks
  - mixup
  - lover
  - vault
  - stans
  - fools
  - balls
  - spawn
  - deals
  - bling
  - yurts
  - month
  - socks
  - bombs
  - champ
  - swede
  - odors
  - force
  - funds
  - swamp
  - brine
  - juice
  - beans
  - slams
  - aroma
  - gorge
  - cysts
  - gully
  - patty
  - baths
  - stage
  - foods
  - skins
  - chips
  - plonk
  - twins
  - teeth
  - tower
  - shack
  - hyena
  - titan
  - takes
  - foots
  - lemon
  - crows
  - chute
  - bongs
  - heist
  - sword
  - kayak
  - droid
  - owner
  - paste
  - mayor
  - syrup
  - crime
  - snake
  - snark
  - bliss
